// Generated by CoffeeScript 1.9.3
(function() {
  var matchFilter, setupFilters, setupTable, updateFilters, updateTable;

  matchFilter = function(filter, value) {
    var logic, pattern;
    pattern = filter['pattern'];
    logic = filter['logic'];
    console.log(pattern, logic);
    if (logic === null) {
      return true;
    } else if (logic === 'text') {
      return value.toLowerCase().includes(pattern.toLowerCase());
    } else if (logic === 'numeric') {
      value = value.replace(",", "");
      if (/^\d/.test(pattern)) {
        return value.includes(pattern);
      }
      return eval(value + pattern);
    }
    return true;
  };

  updateTable = function(table) {
    var cellsWithPatterns, patterns;
    cellsWithPatterns = $(table).find('thead tr[has-filter-inputs] th');
    patterns = cellsWithPatterns.map(function(idx, cell) {
      if ($(cell).children('input').length > 0) {
        return {
          pattern: $(cell).children('input').val(),
          logic: $(cell).children('input').attr('filter-logic')
        };
      }
      return {
        logic: null
      };
    }).toArray();
    $(table).find('tbody tr').each(function(j, row) {
      var i, rowCells;
      rowCells = $(row).find('td');
      $(row).show();
      i = 0;
      while (i < rowCells.length) {
        if (!matchFilter(patterns[i], $(rowCells[i]).text())) {
          $(row).hide();
        }
        i++;
      }
    });
  };

  updateFilters = function() {
    return $('table[is-filterable]').each(function(i, table) {
      return updateTable(table);
    });
  };

  setupTable = function(t) {
    $(t).find('thead').append('<tr has-filter-inputs></tr>');
    $(t).find('thead tr[has-column-names] th').each(function(i, elem) {
      if ($(elem).is('[is-filter]')) {
        return $(t).find('thead tr[has-filter-inputs]').append('<th><input filter-logic=\'' + $(elem).attr('filter-logic') + '\'></input></th>');
      } else {
        return $(t).find('thead tr[has-filter-inputs]').append('<th></th>');
      }
    });
    return $('table[is-filterable] thead tr th input').change(function() {
      return updateFilters();
    });
  };

  setupFilters = function() {
    $('table[is-filterable]').each(function() {
      setupTable(this);
    });
  };

  $(document).ready(setupFilters);

}).call(this);
