matchFilter = (filter, value) ->
  pattern = filter['pattern']
  logic = filter['logic']
  console.log pattern, logic
  if logic == null
    return true
  else if logic == 'text'
    return value.toLowerCase().includes(pattern.toLowerCase())
  else if logic == 'numeric'
    value = value.replace(",", "")
    if /^\d/.test(pattern)
      return value.includes(pattern)
    return eval(value + pattern)
  return true

updateTable = (table) ->
  # Make an array with the cells with filter inputs
  cellsWithPatterns = $(table).find('thead tr[has-filter-inputs] th')
  # Read patterns from cells into an array of objects
  patterns = cellsWithPatterns.map((idx, cell) ->
    if $(cell).children('input').length > 0
      return {
        pattern: $(cell).children('input').val()
        logic: $(cell).children('input').attr('filter-logic')
      }
    { logic: null }
  ).toArray()
  # Compare each table row to the pattern and
  # hide it
  $(table).find('tbody tr').each (j, row) ->
    rowCells = $(row).find('td')
    $(row).show()
    i = 0
    while i < rowCells.length
      if !matchFilter(patterns[i], $(rowCells[i]).text())
        $(row).hide()
      i++
    return
  return

updateFilters = ->
  $('table[is-filterable]').each (i, table) ->
    updateTable table

setupTable = (t) ->
  $(t).find('thead').append '<tr has-filter-inputs></tr>'
  $(t).find('thead tr[has-column-names] th').each (i, elem) ->
    if $(elem).is('[is-filter]')
      $(t).find('thead tr[has-filter-inputs]').append '<th><input filter-logic=\'' + $(elem).attr('filter-logic') + '\'></input></th>'
    else
      $(t).find('thead tr[has-filter-inputs]').append '<th></th>'
  $('table[is-filterable] thead tr th input').change ->
    updateFilters()

setupFilters = ->
  $('table[is-filterable]').each ->
    setupTable this
    return
  return

$(document).ready setupFilters

# ---
# generated by js2coffee 2.0.4